### ISSUE TITLE
Needed: Instructions for making and changing directories

### ISSUE THREAD

**Issue by lisawilliams** [fullstackjournalists/intro-to-coding-for-journalists#3]
Need basic Bash commands

**Comment by macloo** [comment]
Use any or all of this Google doc - http://bit.ly/mm-commandline

**Comment by lisawilliams** [comment]
Changes included in this commit: https://github.com/fullstackjournalists/intro-to-coding-for-journalists/commit/4d57d9dd73e87ec33514da99aeb89c8594b74728
